# Generated by Django 4.2.1 on 2023-05-10 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('tconst', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('titleType', models.CharField(max_length=100)),
                ('primaryTitle', models.CharField(max_length=255)),
                ('runtimeMinutes', models.IntegerField()),
                ('genres', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('tconst', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='test_task.movies')),
                ('averageRating', models.FloatField()),
                ('numVotes', models.IntegerField()),
            ],
        ),
    ]
