# Generated by Django 4.2.1 on 2023-05-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='tconst',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
