# Generated by Django 4.2.1 on 2023-05-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_task', '0002_alter_ratings_tconst'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='averageRating',
            field=models.FloatField(default=0.0),
        ),
    ]
